In [4]:
time_horizon_in_years = 10
discount_rate_as_percent_per_year = 10

In [5]:
# demographic_table
population_count = 1000
population_growth_rate_as_percent_per_year = 10

In [6]:
# Compute the population at year zero
population_count

1000

In [7]:
# Compute the population at year one
population_count * (1 + population_growth_rate_as_percent_per_year / 100.)

1100.0

In [8]:
# Compute the population at year two
population_count * (1 + population_growth_rate_as_percent_per_year / 100.) ** 2

1210.0000000000002

In [9]:
projected_population_count = population_count * (
    1 + population_growth_rate_as_percent_per_year / 100.
) ** time_horizon_in_years
projected_population_count

2593.7424601000025

In [11]:
population_by_year = {
    2000: 1000,
    2010: 2000,
}

In [13]:
from pandas import Series
Series(population_by_year)

2000    1000
2010    2000
dtype: int64

In [15]:
t = DataFrame({'population': population_by_year})
t

population
2000        1000
2010        2000

In [26]:
x = t['population']
x

2000    1000
2010    2000
Name: population, dtype: int64

In [28]:
x.values

array([1000, 2000])

In [32]:
x = Series(index=[2000, 2010])
x

2000   NaN
2010   NaN
dtype: float64

In [36]:
x.reset_index()

index   0
0   2000 NaN
1   2010 NaN

In [39]:
years = Series([2000, 2010])

In [42]:
2 * years

0    4000
1    4020
dtype: int64

In [44]:
time_horizon_in_years = 10
financing_year = 2000
base_population = 1000
population_growth_rate_as_percent_per_year = 10

In [45]:
year_increments = Series(range(time_horizon_in_years + 1))
year_increments

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [47]:
years = financing_year + year_increments
years

0     2000
1     2001
2     2002
3     2003
4     2004
5     2005
6     2006
7     2007
8     2008
9     2009
10    2010
dtype: int64

In [49]:
def grow_exponentially(value, growth_rate_as_percent, growth_count):
    return value * (1 + growth_rate_as_percent / 100.) ** growth_count

populations = grow_exponentially(
    base_population, population_growth_rate_as_percent_per_year, year_increments)
populations

0     1000.000000
1     1100.000000
2     1210.000000
3     1331.000000
4     1464.100000
5     1610.510000
6     1771.561000
7     1948.717100
8     2143.588810
9     2357.947691
10    2593.742460
dtype: float64

In [50]:
populations.index = years
populations

2000    1000.000000
2001    1100.000000
2002    1210.000000
2003    1331.000000
2004    1464.100000
2005    1610.510000
2006    1771.561000
2007    1948.717100
2008    2143.588810
2009    2357.947691
2010    2593.742460
dtype: float64

In [51]:
populations.index = year_increments

In [55]:
populations

0     1000.000000
1     1100.000000
2     1210.000000
3     1331.000000
4     1464.100000
5     1610.510000
6     1771.561000
7     1948.717100
8     2143.588810
9     2357.947691
10    2593.742460
dtype: float64

In [61]:
populations.max()

2593.7424601000025

In [56]:
years

0     2000
1     2001
2     2002
3     2003
4     2004
5     2005
6     2006
7     2007
8     2008
9     2009
10    2010
dtype: int64

In [10]:
connection_count_per_thousand_people = 120
consumption_per_connection_in_kwh = 456

In [95]:
from math import ceil
projected_connection_count = \
    projected_population_count * connection_count_per_thousand_people / 1000.
int(ceil(projected_connection_count))

312

In [12]:
projected_consumption_in_kwh = \
    consumption_per_connection_in_kwh * projected_connection_count
projected_consumption_in_kwh

141929.58741667215

In [7]:
def f(**kw):
    print kw
    
f(x=1, y=2)

{'y': 2, 'x': 1}


In [2]:
import inspect

In [4]:
x = inspect.getargspec(f)
x

ArgSpec(args=[], varargs=None, keywords='kw', defaults=None)

In [5]:
x.keywords

'kw'

In [2]:
# def adjust_for_loss(x, *loss_as_fractions):
# def adjust_for_loss(x, *losses_as_fractions):
# def adjust_for_loss(x, *fraction_losses):
def adjust_for_losses(x, *fractional_losses):

    def adjust_for_loss(x, fractional_loss):
        divisor = 1 - fractional_loss
        if not divisor:
            return x
        return x / float(divisor)
        
    y = x
    for fractional_loss in fractional_losses:
        y = adjust_for_loss(y, fractional_loss)
    return y

adjust_for_losses(100, 0.1, 0.1)

123.45679012345678

In [ ]:
adjust_for_losses()

In [ ]:
grid_system_loss_as_percent = 15
medium_voltage_transformer_load_power_factor = 0.85

In [29]:
projected_consumption_in_kwh

141929.58741667215

In [37]:
projected_production_in_kwh = adjust_for_losses(
    projected_consumption_in_kwh,
    grid_system_loss_as_percent / 100.,
    1 - medium_voltage_transformer_load_power_factor)
projected_production_in_kwh

196442.33552480576

In [38]:
remote_electricity_production_cost_in_dollars_per_kwh = 0.17
remote_electricity_production_cost_in_dollars = \
    remote_electricity_production_cost_in_dollars_per_kwh * projected_production_in_kwh
remote_electricity_production_cost_in_dollars

33395.19703921698

In [5]:
from pandas import Series
s = Series([
    (2000, 1000),
    (2001, 2000),
])

In [6]:
s

0    (2000, 1000)
1    (2001, 2000)
dtype: object

In [ ]:
def compute_discounted_cash_flow(time_value_packs, discount_rate_percent):
    time_value_packs = sort_time_packs(time_value_packs)
    discount_rate_factor = 1 + discount_rate_percent / 100.
    values = [value for time, value in time_value_packs]
    return sum(x / discount_rate_factor ** t for t, x in enumerate(values))

In [11]:
from pandas import Series

def compute_discounted_cash_flow(cash_flow_by_year, financing_year, discount_rate_as_percent):
    # TODO
    pass

cash_flow_by_year = Series([
    1000,
    1000,
    1000,
    1000,
], index=[2000, 2002, 2004, 2006])
discount_rate_as_percent = 10
financing_year = 2000
compute_discounted_cash_flow(cash_flow_by_year, financing_year, discount_rate_as_percent)

In [12]:
cash_flow_by_year.index

Int64Index([2000, 2002, 2004, 2006], dtype='int64')

In [15]:
cash_flow_by_year.index < 0

array([False, False, False, False], dtype=bool)

In [35]:
x = Series()
x.empty

True

In [23]:
import numpy as np
financing_year = 2003
year_increments = np.array(cash_flow_by_year.index - financing_year)
year_increments

array([-3, -1,  1,  3])

In [26]:
year_increments[year_increments < 0] = 0
year_increments

array([0, 0, 1, 3])

In [28]:
discount_rate_as_factor = 1 + discount_rate_as_percent / 100.
discount_rate_as_factor

1.1

In [32]:
sum(cash_flow_by_year / discount_rate_as_factor ** year_increments)

3660.4057099924867

In [31]:
np.array([2, 3, 4]) ** np.array([1, 2, 3])

array([ 2,  9, 64])

In [21]:


def compute_discounted_cash_flow(time_value_packs, discount_rate_percent):
    time_value_packs = sort_time_packs(time_value_packs)
    discount_rate_factor = 1 + discount_rate_percent / 100.
    values = [value for time, value in time_value_packs]
    return sum(x / discount_rate_factor ** t for t, x in enumerate(values))

Int64Index([-3, -1], dtype='int64')

In [ ]:
cash_flow_by_year_increment

In [116]:
# Medium Voltage Transformer

"""
Initial Installation Cost
The cost of a transformer depends on its capacity, which is how much electricity it can deliver.
Transformer capacity is listed in kVA.
If the power factor of the load is 0.85, then the number of kWh delivered is kVA * 0.85.
Size transformer capacity based on estimated peak demand.

Estimate the amount of loss-adjusted consumption that is happening during peak hours.
Divide the loss-adjusted consumption by the number of peak hours per year to estimate peak demand.

Select the largest transformer capacity that will satisfy the estimated peak demand.
Estimate the number of those transformers that will satisfy the estimated peak demand.
Estimate the installation cost by multiplying the installation cost of the selected transformer by the number of transformers.

Recurring Maintenance Cost
Multiply the maintenance cost per year of the selected transformer by the number of transformers.

Recurring Replacement Cost
Divide the installation cost by the lifetime of the selected transformer.
""";

In [40]:
# Get the transformer table
from pandas import DataFrame
medium_voltage_transformer_table = DataFrame([
    (1, 1000, 30, 10),
    (10, 15000, 450, 12),
], columns=[
    'Capacity (kVA)',
    'Installation Labor and Material Cost ($)',
    'Maintenance Labor and Material Cost ($/year)',
    'Lifetime (years)'        
])
medium_voltage_transformer_table

Capacity (kVA)  Installation Labor and Material Cost ($)  \
0               1                                      1000   
1              10                                     15000   

   Maintenance Labor and Material Cost ($/year)  Lifetime (years)  
0                                            30                10  
1                                           450                12

In [41]:
projected_production_in_kwh

NameError: name 'projected_production_in_kwh' is not defined

In [42]:
peak_hours_of_production_per_year = 1460
consumption_during_peak_hours_as_percent_of_total_consumption = 40

In [43]:
def estimate_peak_demand_in_kilowatts(
        consumption_in_kilowatt_hours_by_year,
        consumption_during_peak_hours_as_percent_of_total_consumption,
        peak_hours_of_consumption_per_year):
    maximum_consumption_per_year_in_kilowatt_hours = \
        max([x[1] for x in consumption_in_kilowatt_hours_by_year.items()])
    consumption_during_peak_hours_in_kilowatt_hours = \
        maximum_consumption_per_year_in_kilowatt_hours * \
        consumption_during_peak_hours_as_percent_of_total_consumption / 100.
    return consumption_during_peak_hours_in_kilowatt_hours / float(peak_hours_of_consumption_per_year)

In [44]:
estimate_peak_demand_in_kilowatts({2000: 100, 2015: 200}, 40, 1490)

0.053691275167785234

In [45]:
estimate_peak_demand_in_kilowatts({2000: 1000}, 40, 1490)

0.2684563758389262

In [46]:
estimate_peak_demand_in_kilowatts({2000: 100}, 40, 1490) * 10

0.2684563758389262

In [47]:
production_during_peak_hours_in_kwh = \
    projected_production_in_kwh * consumption_during_peak_hours_as_percent_of_total_consumption / 100.
production_during_peak_hours_in_kwh

NameError: name 'projected_production_in_kwh' is not defined

In [48]:
peak_demand_in_kw = production_during_peak_hours_in_kwh / float(peak_hours_of_production_per_year)
peak_demand_in_kw

NameError: name 'production_during_peak_hours_in_kwh' is not defined

In [52]:
peak_demand_in_kw = 100
desired_system_capacity_in_kw = peak_demand_in_kw

In [53]:
transformer_table = medium_voltage_transformer_table
capacity_column = 'Capacity (kVA)'

In [54]:
# Choose transformer type
eligible_transformer_table = transformer_table[
    transformer_table[capacity_column] < desired_system_capacity_in_kw]
eligible_transformer_table

Capacity (kVA)  Installation Labor and Material Cost ($)  \
0               1                                      1000   
1              10                                     15000   

   Maintenance Labor and Material Cost ($/year)  Lifetime (years)  
0                                            30                10  
1                                           450                12

In [55]:
if len(eligible_transformer_table):
    selected_transformer_table = eligible_transformer_table[
        eligible_transformer_table[
            capacity_column
        ] == eligible_transformer_table[
            capacity_column
        ].max()]
else:
    selected_transformer_table = transformer_table[
        transformer_table[
            capacity_column
        ] == transformer_table[
            capacity_column
        ].min()]    
selected_transformer = selected_transformer_table.ix[selected_transformer_table.index[0]]
selected_transformer

Capacity (kVA)                                     10
Installation Labor and Material Cost ($)        15000
Maintenance Labor and Material Cost ($/year)      450
Lifetime (years)                                   12
Name: 1, dtype: int64

In [56]:
selected_transformer[capacity_column]

10

In [77]:
selected_transformer_capacity_in_kw = selected_transformer_table[capacity_column].values[0]
selected_transformer_capacity_in_kw

10

In [78]:
# Get selected_transformer_count
from math import ceil
selected_transformer_count = int(ceil(
    desired_system_capacity_in_kw / float(selected_transformer_capacity_in_kw)))
selected_transformer_count

6

In [91]:
installation_cost_per_transformer = selected_transformer_table[
    'Installation Labor and Material Cost ($)'].values[0]
installation_cost = installation_cost_per_transformer * selected_transformer_count
installation_cost

90000

In [92]:
maintenance_cost_per_year_per_transformer = selected_transformer_table[
    'Maintenance Labor and Material Cost ($/year)'].values[0]
maintenance_cost_per_year = maintenance_cost_per_year_per_transformer * selected_transformer_count
maintenance_cost_per_year

2700

In [94]:
lifetime_in_years = selected_transformer_table[
    'Lifetime (years)'].values[0]
replacement_cost_per_year = installation_cost / float(lifetime_in_years)
replacement_cost_per_year

7500.0

In [ ]:
"""
Low Voltage Line

Initial Installation Cost
Multiply the installation cost of LV line per meter by the estimated number of meters of LV line.
The number of meters of LV line is the number of connections multiplied by the average distance between buildings.

Recurring Maintenance Cost
Multiply the maintenance cost of LV line per meter by the number of meters of LV line.

Recurring Replacement Cost
Divide the installation cost by the lifetime of LV line.

low voltage line
    installation cost = $10 / meter
    maintenance cost = $0.10 / meter / year
    lifetime = 10 years
average distance between buildings = 25 meters
"""

In [97]:
low_voltage_line_installation_labor_and_material_cost_in_dollars_per_meter = 0.10
low_voltage_line_maintenance_labor_and_material_cost_in_dollars_per_meter_per_year = 0.10
low_voltage_line_lifetime_in_years = 10
average_distance_between_buildings_in_meters = 25

In [101]:
low_voltage_line_length_in_meters = \
    (projected_connection_count - 1) * average_distance_between_buildings_in_meters
low_voltage_line_length_in_meters

7756.227380300008

In [104]:
low_voltage_line_installation_labor_and_material_cost_in_dollars = \
    low_voltage_line_installation_labor_and_material_cost_in_dollars_per_meter * low_voltage_line_length_in_meters
low_voltage_line_installation_labor_and_material_cost_in_dollars

775.6227380300008

In [105]:
low_voltage_line_maintenance_labor_and_material_cost_in_dollars_per_meter_per_year * low_voltage_line_length_in_meters

775.6227380300008

In [107]:
low_voltage_line_replacement_labor_and_material_cost_in_dollars_per_year = \
    low_voltage_line_installation_labor_and_material_cost_in_dollars / float(low_voltage_line_lifetime_in_years)
low_voltage_line_replacement_labor_and_material_cost_in_dollars_per_year

In [ ]:
"""
Low Voltage Connection

Initial Installation Cost
Multiply the installation cost per connection by the estimated number of connections.

Recurring Maintenance Cost
Multiply the maintenance cost per connection by the estimated number of connections.

Recurring Replacement Cost
Divide the installation cost by the lifetime of the connection to estimate the replacement cost per year.

low voltage connection     
    installation cost = $330 / connection        
    maintenance cost = $3.00 / connection / year    
    lifetime = 10 years
"""

In [108]:
low_voltage_connection_installation_cost_per_connection = 330
low_voltage_connection_maintenance_cost_per_connection_per_year = 3
low_voltage_connection_lifetime_in_years = 10

In [115]:
low_voltage_connection_installation_cost = \
    low_voltage_connection_installation_cost_per_connection * projected_connection_count
low_voltage_connection_installation_cost

102712.20141996011

In [113]:
low_voltage_connection_maintenance_cost_per_connection_per_year * projected_connection_count

933.7472856360009

In [114]:
low_voltage_connection_installation_cost / float(
    low_voltage_connection_lifetime_in_years)

10271.220141996011

In [2]:
from pandas import Series
s = Series([1, 2, 3], index=[2000, 2001, 2002])

In [3]:
s

2000    1
2001    2
2002    3
dtype: int64

In [4]:
s.values

array([1, 2, 3])

In [5]:
max(s)

3

In [6]:
s.max()

3