In [41]:
# Decide tool name
# Estimate levelized cost of elecricity from grid before network

In [ ]:
"""
estimate pre-network technology cost of electricity
estimate levelized cost of electricity from grid before network
estimate electricity cost from grid before network
"""

In [ ]:
"""
Given demand by year, estimate cost by year, discounted cost, levelized cost.

PRODUCTION
Electricity production cost per year 
$/yr
is proportional to consumption per year
is proportional to distribution loss

MEDIUM VOLTAGE
Line
Years 0-X Initial Cost (Labor + Material)
Years X-Y Recurring Costs (Labor + Material)

LOW VOLTAGE
Transformer (sized using multiples of largest available capacity)
Years 0-X Initial Cost (Labor + Material)
Years X-Y Recurring Costs (Labor + Material)

Line
Years 0-X Initial Cost (Labor + Material)
Years X-Y Recurring Costs (Labor + Material)
"""

In [ ]:
"""
Consumption by year table
Production cost per kilowatt hour
Medium voltage line
installation
labor cost in dollars
material cost in dollars
time in years
maintenance
labor cost in dollars
material cost in dollars
time in years
replacement
labor cost in dollars
material cost in dollars
time in years
Low voltage transformer
Low voltage line
"""

In [ ]:
"""
+ Discounted cost (pre-network grid discounted cost)
= Levelized cost (pre-network grid levelized cost)
Cost by year table (pre-network grid cost by year table)
    Year
    Cost (Populate initial, recurring, replacement costs by year)
    Production Cost

    Medium Voltage Line Labor Cost
    Medium Voltage Line Material Cost

    Low Voltage Transformer Labor Cost
    Low Voltage Transformer Material Cost

    Low Voltage Line Labor Cost
    Low Voltage Line Material Cost
"""

In [4]:
from pandas import DataFrame
cost_by_year_table = DataFrame([
    [2020, 10000],
    [2021, 10000],
    [2022, 5000],
    [2023, 5000],
    [2024, 5000],
], columns=[
    'Year', 'Cost ($)',
])
discount_rate_percent = 10

In [5]:
# Discounted cost
from infrastructure_planning.finance.valuation import compute_discounted_cash_flow
discounted_cost = compute_discounted_cash_flow(
    cost_by_year_table[['Year', 'Cost ($)']].values,
    discount_rate_percent)
discounted_cost

30394.781777201009

In [6]:
# Levelized cost
consumption_by_year_table = DataFrame([
    [2020, 10000],
    [2021, 50000],
    [2022, 99999],
    [2023, 99999],
    [2024, 99999],
], columns=[
    'Year', 'Consumption (kWh)',
])

In [7]:
discounted_consumption = compute_discounted_cash_flow(
    consumption_by_year_table[['Year', 'Consumption (kWh)']].values,
    discount_rate_percent)
discounted_consumption

281529.73840584652

In [8]:
levelized_cost = discounted_cost / float(
    discounted_consumption) if discounted_consumption else 0
levelized_cost

0.10796295250835854

In [9]:
# Get production_cost

In [10]:
# _ Option 1: Row calculation
# = Option 2: Table calculation

In [11]:
self.get(
    GridElectricityCostPerKilowattHour) * self.get(
    demand.ProjectedNodalDemandPerYear) / float(1 - self.get(DistributionLoss))

NameError: name 'self' is not defined

In [12]:
# consumption_by_year_table
year_column = 'Year'
consumption_column = 'Consumption (kWh)'

In [13]:
distribution_loss_percent = 15
grid_electricity_cost_in_dollars_per_kilowatt_hour = 0.15

In [14]:
consumption_by_year_table[
    'Production Cost ($)'
] = grid_electricity_cost_in_dollars_per_kilowatt_hour * consumption_by_year_table[
    consumption_column
] / float(1 - distribution_loss_percent / 100.)

In [15]:
consumption_by_year_table

Year  Consumption (kWh)  Production Cost ($)
0  2020              10000          1764.705882
1  2021              50000          8823.529412
2  2022              99999         17646.882353
3  2023              99999         17646.882353
4  2024              99999         17646.882353

In [16]:
# Get low voltage transformer cost
# Labor
# Material

# grid_low_voltage_transformer_installation_material_cost_in_dollars
# Low Voltage Transformer Installation Material Cost ($)

"""
installation
    labor cost in dollars
    material cost in dollars
    time in years
maintenance
    labor cost in dollars
    material cost in dollars
    time in years
replacement
    labor cost in dollars
    material cost in dollars
    time in years
"""

'\ninstallation\n    labor cost in dollars\n    material cost in dollars\n    time in years\nmaintenance\n    labor cost in dollars\n    material cost in dollars\n    time in years\nreplacement\n    labor cost in dollars\n    material cost in dollars\n    time in years\n'

In [17]:
# + Translate components into variable names
# = Identify equivalents from old model
# Place into table

In [18]:
grid_low_voltage_transformer_installation_labor_cost_in_dollars_per_year = 500000
grid_low_voltage_transformer_installation_material_cost_in_dollars = 100000
grid_low_voltage_transformer_installation_time_in_years = 2

grid_low_voltage_transformer_maintenance_labor_cost_in_dollars_per_year = 50000
grid_low_voltage_transformer_maintenance_material_cost_in_dollars_per_year = 1000
grid_low_voltage_transformer_maintenance_time_in_years = 10

grid_low_voltage_transformer_replacement_labor_cost_in_dollars_per_year = 50000
grid_low_voltage_transformer_replacement_material_cost_in_dollars = 150000
grid_low_voltage_transformer_replacement_time_in_years = 3

In [19]:
# consumption_by_year_table
# ... above variables

# Given a number of years, generate array that we can just assign as a column in the table

In [20]:
# Is it safe to assume that there are no duplicate years?
consumption_by_year_table

Year  Consumption (kWh)  Production Cost ($)
0  2020              10000          1764.705882
1  2021              50000          8823.529412
2  2022              99999         17646.882353
3  2023              99999         17646.882353
4  2024              99999         17646.882353

In [21]:
from pandas import DataFrame
df = DataFrame([
    [2020, 'one'],
    [2020, 'two'],
    [2021, 'three'],
    [2022, 'four'],
], columns=[
    'Year', 'Value',
])
df

Year  Value
0  2020    one
1  2020    two
2  2021  three
3  2022   four

In [22]:
# We need to do this for the initial consumption table
df.drop_duplicates('Year')

Year  Value
0  2020    one
2  2021  three
3  2022   four

In [23]:
len(consumption_by_year_table)

5

In [24]:
year_count = 30

installation_labor_cost_in_dollars_per_year = 500000
installation_material_cost_in_dollars = 100000
installation_time_in_years = 2

maintenance_labor_cost_in_dollars_per_year = 50000
maintenance_material_cost_in_dollars_per_year = 1000
maintenance_time_in_years = 10

replacement_labor_cost_in_dollars_per_year = 50000
replacement_material_cost_in_dollars = 150000
replacement_time_in_years = 3

In [25]:
from pandas import DataFrame

In [26]:
prefix = 'LV Transformer'
table = DataFrame({
    prefix + ' Installation Labor Cost ($)': [],
    prefix + ' Installation Material Cost ($)': [],
    prefix + ' Maintenance Labor Cost ($)': [],
    prefix + ' Maintenance Material Cost ($)': [],
    prefix + ' Replacement Labor Cost ($)': [],
    prefix + ' Replacement Material Cost ($)': [],
})
table

Empty DataFrame
Columns: [LV Transformer Installation Labor Cost ($), LV Transformer Installation Material Cost ($), LV Transformer Maintenance Labor Cost ($), LV Transformer Maintenance Material Cost ($), LV Transformer Replacement Labor Cost ($), LV Transformer Replacement Material Cost ($)]
Index: []

In [27]:
import numpy as np
installation_labor_costs = np.zeros(year_count)
installation_labor_costs

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [28]:
import numpy as np
installation_labor_costs = np.zeros(year_count)
installation_labor_costs[:installation_time_in_years] = installation_labor_cost_in_dollars_per_year
installation_labor_costs

array([ 500000.,  500000.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.])

In [29]:
installation_material_costs = np.zeros(year_count)
installation_material_costs[0] = installation_material_cost_in_dollars
installation_material_costs

array([ 100000.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.])

In [30]:
year_count = 30

installation_labor_cost_in_dollars_per_year = 500000
installation_material_cost_in_dollars = 100000
installation_time_in_years = 2

maintenance_labor_cost_in_dollars_per_year = 50000
maintenance_material_cost_in_dollars_per_year = 1000
maintenance_time_in_years = 10

replacement_labor_cost_in_dollars_per_year = 50000
replacement_material_cost_in_dollars = 150000
replacement_time_in_years = 3

In [31]:
x = np.zeros(year_count)
x

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.])

In [32]:
x[29]

0.0

In [33]:
x[30:31]

array([], dtype=float64)

In [35]:
maintenance_labor_costs = np.zeros(year_count)
maintenance_labor_costs[installation_time_in_years:] = maintenance_labor_cost_in_dollars_per_year
maintenance_labor_costs

array([     0.,      0.,  50000.,  50000.,  50000.,  50000.,  50000.,
        50000.,  50000.,  50000.,  50000.,  50000.,  50000.,  50000.,
        50000.,  50000.,  50000.,  50000.,  50000.,  50000.,  50000.,
        50000.,  50000.,  50000.,  50000.,  50000.,  50000.,  50000.,
        50000.,  50000.])

In [43]:
maintenance_material_costs = np.zeros(year_count)
maintenance_material_costs[installation_time_in_years:] = maintenance_material_cost_in_dollars_per_year
maintenance_material_costs

array([    0.,     0.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,
        1000.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,
        1000.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,  1000.,
        1000.,  1000.,  1000.,  1000.,  1000.,  1000.])

In [39]:
replacement_labor_costs = np.zeros(year_count)
index1 = installation_time_in_years + maintenance_time_in_years
index2 = index1 + replacement_time_in_years
while index1 < year_count:
    replacement_labor_costs[index1:index2] = replacement_labor_cost_in_dollars_per_year
    index1 = index2 + maintenance_time_in_years
    index2 = index1 + replacement_time_in_years
replacement_labor_costs

array([     0.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,      0.,  50000.,  50000.,
        50000.,      0.,      0.,      0.,      0.,      0.,      0.,
            0.,      0.,      0.,      0.,  50000.,  50000.,  50000.,
            0.,      0.])

In [42]:
replacement_material_costs = np.zeros(year_count)
index1 = installation_time_in_years + maintenance_time_in_years
while index1 < year_count:
    replacement_material_costs[index1] = replacement_material_cost_in_dollars
    index1 += maintenance_time_in_years + replacement_time_in_years
replacement_material_costs

array([      0.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
        150000.,       0.,       0.,       0.,       0.,       0.,
             0.,       0.,       0.,       0.,       0.,       0.,
             0.,  150000.,       0.,       0.,       0.,       0.])

In [44]:
prefix = 'LV Transformer'
table = DataFrame({
    prefix + ' Installation Labor Cost ($)': installation_labor_costs,
    prefix + ' Installation Material Cost ($)': installation_material_costs,
    prefix + ' Maintenance Labor Cost ($)': maintenance_labor_costs,
    prefix + ' Maintenance Material Cost ($)': maintenance_material_costs,
    prefix + ' Replacement Labor Cost ($)': replacement_labor_costs,
    prefix + ' Replacement Material Cost ($)': replacement_material_costs,
})
table

LV Transformer Installation Labor Cost ($)  \
0                                       500000   
1                                       500000   
2                                            0   
3                                            0   
4                                            0   
5                                            0   
6                                            0   
7                                            0   
8                                            0   
9                                            0   
10                                           0   
11                                           0   
12                                           0   
13                                           0   
14                                           0   
15                                           0   
16                                           0   
17                                           0   
18                                           0   
19                                           0   
20                                           0   
21                                           0   
22                                           0   
23                                           0   
24                                           0   
25                                           0   
26                                           0   
27                                           0   
28                                           0   
29                                           0   

    LV Transformer Installation Material Cost ($)  \
0                                          100000   
1                                               0   
2                                               0   
3                                               0   
4                                               0   
5                                               0   
6                                               0   
7                                               0   
8                                               0   
9                                               0   
10                                              0   
11                                              0   
12                                              0   
13                                              0   
14                                              0   
15                                              0   
16                                              0   
17                                              0   
18                                              0   
19                                              0   
20                                              0   
21                                              0   
22                                              0   
23                                              0   
24                                              0   
25                                              0   
26                                              0   
27                                              0   
28                                              0   
29                                              0   

    LV Transformer Maintenance Labor Cost ($)  \
0                                           0   
1                                           0   
2                                       50000   
3                                       50000   
4                                       50000   
5                                       50000   
6                                       50000   
7                                       50000   
8                                       50000   
9                                       50000   
10                                      50000   
11                                      50000   
12                                      50000   
13                                      50000   
14                                      50000   
15                       

In [ ]:
year_count = 30

installation_labor_cost_in_dollars_per_year = 500000
installation_material_cost_in_dollars = 100000
installation_time_in_years = 2

maintenance_labor_cost_in_dollars_per_year = 50000
maintenance_material_cost_in_dollars_per_year = 1000
maintenance_time_in_years = 10

replacement_labor_cost_in_dollars_per_year = 50000
replacement_material_cost_in_dollars = 150000
replacement_time_in_years = 3

In [47]:
import numpy as np

def get_cost_breakdown_table(
        prefix,
        year_count,
        installation_labor_cost_in_dollars_per_year,
        installation_material_cost_in_dollars,
        installation_time_in_years,
        maintenance_labor_cost_in_dollars_per_year,
        maintenance_material_cost_in_dollars_per_year,
        maintenance_time_in_years,
        replacement_labor_cost_in_dollars_per_year,
        replacement_material_cost_in_dollars,
        replacement_time_in_years):

    installation_labor_costs = np.zeros(year_count)
    installation_labor_costs[:installation_time_in_years] = installation_labor_cost_in_dollars_per_year

    installation_material_costs = np.zeros(year_count)
    installation_material_costs[0] = installation_material_cost_in_dollars

    maintenance_labor_costs = np.zeros(year_count)
    maintenance_labor_costs[installation_time_in_years:] = maintenance_labor_cost_in_dollars_per_year

    maintenance_material_costs = np.zeros(year_count)
    maintenance_material_costs[installation_time_in_years:] = maintenance_material_cost_in_dollars_per_year

    replacement_labor_costs = np.zeros(year_count)
    index1 = installation_time_in_years + maintenance_time_in_years
    index2 = index1 + replacement_time_in_years
    while index1 < year_count:
        replacement_labor_costs[index1:index2] = replacement_labor_cost_in_dollars_per_year
        index1 = index2 + maintenance_time_in_years
        index2 = index1 + replacement_time_in_years

    replacement_material_costs = np.zeros(year_count)
    index1 = installation_time_in_years + maintenance_time_in_years
    while index1 < year_count:
        replacement_material_costs[index1] = replacement_material_cost_in_dollars
        index1 += maintenance_time_in_years + replacement_time_in_years
    replacement_material_costs

    return DataFrame({
        prefix + ' Installation Labor Cost ($)': installation_labor_costs,
        prefix + ' Installation Material Cost ($)': installation_material_costs,
        prefix + ' Maintenance Labor Cost ($)': maintenance_labor_costs,
        prefix + ' Maintenance Material Cost ($)': maintenance_material_costs,
        prefix + ' Replacement Labor Cost ($)': replacement_labor_costs,
        prefix + ' Replacement Material Cost ($)': replacement_material_costs,
    })

get_cost_breakdown_table(
    prefix='LV Transformer',
    year_count=30,
    installation_labor_cost_in_dollars_per_year=500000,
    installation_material_cost_in_dollars=100000,
    installation_time_in_years=2,
    maintenance_labor_cost_in_dollars_per_year=50000,
    maintenance_material_cost_in_dollars_per_year=1000,
    maintenance_time_in_years=5,
    replacement_labor_cost_in_dollars_per_year=50000,
    replacement_material_cost_in_dollars=150000,
    replacement_time_in_years=3)

LV Transformer Installation Labor Cost ($)  \
0                                       500000   
1                                       500000   
2                                            0   
3                                            0   
4                                            0   
5                                            0   
6                                            0   
7                                            0   
8                                            0   
9                                            0   
10                                           0   
11                                           0   
12                                           0   
13                                           0   
14                                           0   
15                                           0   
16                                           0   
17                                           0   
18                                           0   
19                                           0   
20                                           0   
21                                           0   
22                                           0   
23                                           0   
24                                           0   
25                                           0   
26                                           0   
27                                           0   
28                                           0   
29                                           0   

    LV Transformer Installation Material Cost ($)  \
0                                          100000   
1                                               0   
2                                               0   
3                                               0   
4                                               0   
5                                               0   
6                                               0   
7                                               0   
8                                               0   
9                                               0   
10                                              0   
11                                              0   
12                                              0   
13                                              0   
14                                              0   
15                                              0   
16                                              0   
17                                              0   
18                                              0   
19                                              0   
20                                              0   
21                                              0   
22                                              0   
23                                              0   
24                                              0   
25                                              0   
26                                              0   
27                                              0   
28                                              0   
29                                              0   

    LV Transformer Maintenance Labor Cost ($)  \
0                                           0   
1                                           0   
2                                       50000   
3                                       50000   
4                                       50000   
5                                       50000   
6                                       50000   
7                                       50000   
8                                       50000   
9                                       50000   
10                                      50000   
11                                      50000   
12                                      50000   
13                                      50000   
14                                      50000   
15                       