In [2]:
from os.path import expanduser
electricity_consumption_per_capita_table_path = expanduser('~/Projects/infrastructure-planning/datasets/usa_electricity_consumption_in_kilowatt_hours_per_capita.csv')

In [4]:
from pandas import read_csv
electricity_consumption_per_capita_table = read_csv(electricity_consumption_per_capita_table_path)

In [5]:
electricity_consumption_per_capita_table

Country Name Country Code  Year  kWh per Capita
0  United States          USA  2012    12954.153262
1  United States          USA  2011    13240.357987
2  United States          USA  2010    13394.014607
3  United States          USA  2009    12913.711429
4  United States          USA  2008    13663.424680
5  United States          USA  2007    13657.449509
6  United States          USA  2006    13583.266959
7  United States          USA  2005    13704.577048
8  United States          USA  2004    13388.589711
9  United States          USA  2003    13307.492009

In [8]:
electricity_consumption_per_capita_table[['Year', 'kWh per Capita']]

Year  kWh per Capita
0  2012    12954.153262
1  2011    13240.357987
2  2010    13394.014607
3  2009    12913.711429
4  2008    13663.424680
5  2007    13657.449509
6  2006    13583.266959
7  2005    13704.577048
8  2004    13388.589711
9  2003    13307.492009

In [16]:
year_count = len(electricity_consumption_per_capita_table)
year_count

10

In [17]:
electricity_consumption_per_capita_table['Year'].values.reshape(year_count, 1)

array([[2012],
       [2011],
       [2010],
       [2009],
       [2008],
       [2007],
       [2006],
       [2005],
       [2004],
       [2003]])

In [24]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(
    electricity_consumption_per_capita_table['Year'].values.reshape(year_count, 1),
    electricity_consumption_per_capita_table['kWh per Capita'])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
model.predict([[2012], [2014], [2015], [2016]])

array([ 13168.70805431,  13074.48775847,  13027.37761055,  12980.26746263])

In [12]:
from pandas import DataFrame, merge
a = DataFrame([[1, 2], [3, 4]], columns=['A', 'B'])
b = DataFrame([[4, 5], [6, 7]], columns=['C', 'D'])

In [13]:
a

A  B
0  1  2
1  3  4

In [14]:
b

C  D
0  4  5
1  6  7

In [16]:
merge(a, b, left_on='B', right_on='C')

A  B  C  D
0  3  4  4  5

In [20]:
a[['A', 'B']].values

array([[1, 2],
       [3, 4]])